
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.GlassyWalk

api-version: 1.13
version: 1.0

author: [Dashie, Freya, KvinneKraft]
name: GlassyWalk

commands:
    glassywalk:
        aliases: [glassywalking, gw, walky, glass, glasswalk]
        description: By KvinneKraft!