settings:
  max-team-members: 8
  max-team-name-length: 12

# Modify collection in memory, every interval write to config.

team-data:
  1:
    team-name: '&dFluffz'
    team-owner: 'uuid'
    team-members:
      - 'uuid 1'
      - 'uuid 2'