# Author: Dashie
# Version: 1.0
name: DashTeams
version: ${project.version}
main: com.kvinnekraft.DashTeams
api-version: 1.16
authors: [Dashie]
website: https://pugpawz.com
# /f add <player_name>  | requires: teams.originator
# + must not be in a faction
# + using permissions as identifiers.
#
# /f kick <player_name> | requires: teams.originator
# + must be in a faction.
# + must be the originator of the faction.
# + using permissions as identifiers.
#
# /f color              | requires: teams.originator
# + must be in a faction.
# + must be the originator of the faction.
# + using permissions as identifiers.
#
# /f disband            | requires: teams.originator
# + must be in a faction.
# + must be the originator of the faction.
# + removes all players from registry.
# + using permissions as identifiers.
#
# /f create <name>      | requires: no permission
# + must not be in a faction.
# + using permissions as identifiers.
#
# /f list               | requires: no permission
#
# /f chat               | requires: no permission
# + must be in a faction.
# + using permissions as identifiers.
# + typing it twice toggles it off. ON/OFF
#
commands:
  DashTeams:
    aliases: [dteams, teams, team, party, faction, f, fac, party, dashteam]
    description: Oh, what is this?