
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.MoreDrops

api-version: 1.13
version: 1.0

commands:
  moredrops:
    aliases: [moredrops, md, moredrop, drops]
    description: By KvinneKraft.

author: [Dashie, KvinneKraft, ME]
name: MoreDrops