# Author: Dashie
# Version: 2.0
properties:
  auto-reload: true
  reload-interval: 5
craft-settings:
  ignore-permission: craft.bypass
  disable-crafting: false
  blocked-recipes:
    - 'HOPPER'
    - 'IRON_BLOCK'
    - 'CRAFTING_TABLE'