
# Author: Dashie
# Version: 1.0

main: com.dashmobs.DashCash

name: DashCash
author: [Dashie]

version: 1.0
api-version: 1.14

commands:
    dashcash:
        aliases: [dashmobs]
        description: Main command for Dash Mobs 1.0

