name: DashPermsX
version: 1.0
main: com.kvinnekraft.DashPermsX
api-version: 1.16
authors: [Dashie, KvinneKraft, MEEEE, Xemu]
description: Setup permissions man.
website: https://pugpawz.com

commands:
  dashpermsx:
    aliases: [dpx, dashpermissions, dashpermission, dashieperm, dashieperms, dashpermx]
    description: Do you even know man?