
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.AngryBlocks

author: [Dashie, KvinneKraft, Freya]
name: AngryBlocks

api-version: 1.13
version: 1.0

commands:
  angryblocks:
    aliases: [angryblock, ab, hurtfullblocks, ouchyblocks, hurtyblocks]
    description: By KvinneKraft.