
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.FlamyArrows

api-version: 1.13
version: 1.0

author: [Dashie, KvinneKraft, Fluff, Freya, ME]
name: FlamyArrows

commands:
    flamyarrows:
        aliases: [fa, flamearrows, arrowflame, flammyarrows, flamy, flame, arrowflame]
        description: By Ze KvinneKraft.