# Author: Dashie
# Version: 1.0
name: PotionBowX
version: 1.0
main: com.kvinnekraft.PotionBowX
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Shoot potion arrows and such!
website: https://github.com/KvinneKraft

commands:
  potionbowx:
    aliases: [pbx, potionbow, potbow, potbowx, potb]
    description: You do not even know.