# Author: Dashie
# Version: 1.0

name: DashFarming
version: ${project.version}
main: com.kvinnekraft.DashFarming
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Farm crops.  Farm bud.  Farm shrooms.
website: https://pugpawz.com,https://github.com/KvinneKraft

commands:
  DashFarming:
    aliases: [DF, DashFarm, Buds, weed, drug, shrooms, plants, grow, plant]
    description: Oh, what is this?
