

# Author: Dashie
# Version: 1.0


main: com.dashworld.Throwables

api-version: 1.13
version: 1.0

author: [Dashie]
name: DashThrowables

commands:
    dashthrowables:
        aliases: [dashthrow, dt, throwables, throws]