
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.GlassyArrows

version: 1.0
api-version: 1.13

name: GlassyArrows
author: [Dashie, KvinneKraft, Freya, AnyoneWhoHasBeenAPartOfMyLifeMuchLove]

commands:
    glassyarrows:
        aliases: [fa, arrows, breakglass, glassarrows, arrowglass]
        description: Flamy Arrows by KvinneKraft!