
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.MushCraft

api-version: 1.16
version: 1.0

author: [Dashie, KvinneKraft, ME]
name: Mushy

commands:
    mushy:
      aliases: [mushcraft, mush, mushie, mushycraft, mushers, mushn]
      description: Yes. KvinneKraft. Mhm.