# Author: Dashie
# Version: 1.0
name: VoyantMobs
version: 1.0
main: com.kvinnekraft.VoyantMobs
api-version: 1.16
authors: [Dashie]
description: Voyant Mob Creatures
website: https://pugpawz.com

commands:
  VoyantMobs:
    aliases: [vms, voyantm, voyantmob, voyantcreature, fluffycreatures, freyjafluff]
    description: Voyant Mobs
