# Author: Dashie
# Version: 1.0
name: VoyantMobs
version: ${project.version}
main: com.kvinnekraft.VoyantMobs
api-version: 1.16
authors: [Dashie]
description: Voyant Craft Mob Creatures
website: https://pugpawz.com

commands:
  VoyantMobs:
    aliases: []
    description: Oh, what is this?
