
# Author: Dashie
# Version: 1.0

properties:
    effect-permission: 'dashpvp.effects'
        
    effect-list:
        - 'DAMAGE_RESISTANCE 3 5'
        - 'REGENERATION 3 5'
        
    admin-permission: 'dashpvp.admin'        