eat:
  1:
    item-type: BREAD
    item-name: '&6Crossaint'
    item-lore: '&6&oStraight from France.'
    consume-effects:
      - 'REGENERATION 1 20'
    particle-effects: []
    sound-effects: []
    consume-feed: 4
drink:
  1:
    potion-item: 'default'
    potion-color: '10,10,10'
    potion-name: '&eScotch Whiskey'
    consume-effects:
      - 'CONFUSION 1 20'
    particle-effects: []
    sound-effects: []
