# Author: Dashie
# Version: 1.0
name: DashMarket
version: ${project.version}
main: com.kvinnekraft.DashMarket
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Eat, Drink, Sell, Buy and Process
website: https://pugpawz.com
