# Author: Dashie
# Version: 1.0
name: QuickEatX
version: 1.0
main: com.kvinnekraft.QuickEatX
api-version: 1.16
authors: [Dashie, KvinneKraft, ME]
description: Yes.
website: https://github.com/KvinneKraft

commands:
  QuickEatX:
    aliases: [quickeat, qex, quickex]
    description: Oh, you are missing out.