# Author: Dashie
# Version: 1.0
name: DashBossMobSpawn
version: ${project.version}
main: com.kvinnekraft.DashBossMobSpawn
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Custom boss mob spawns
website: https://pugpawz.com