
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.DamageTeleport

author: [Dashie, KvinneKraft, Freya, ALL ME]
name: DamageTeleport

version: 1.0
api-version: 1.13

commands:
  damageteleport:
    aliases: [damagetel, telp, dtp, damagetp, damageteleporter]
    description: By KvinneKraft.