# Author: Dashie
# Version: 1.0
name: DashSigns
version: ${project.version}
main: com.kvinnekraft.DashSigns
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Dashies Command Signs
website: https://pugpawz.com

commands:
  DashSigns:
    aliases: []
    description: Oh, what is this?
