# Author: Dashie
# Version: 1.0
name: PotionObtainablesX
version: 1.0
main: com.kvinnekraft.PotionObtainablesX
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Add as many drugs as you can imagine.
website: https://github.com/KvinneKraft

commands:
  potionobtainablesx:
    aliases: [obtainablesx, potobtainables, potionobtainables, potionox]
    description: Potions man, yea man.
