
# Author: Dashie
# Version: 2.1

main: com.kvinnekraft.BetterCaptcha

version: 2.2
api-version: 1.16

name: BetterDashCaptcha
author: [Dashie, KvinneKraft, Freya, Princess_Freya, Majesty_Freya]

commands:
    dashcaptcha:
        aliases: [dc, captcha, dashrobot, robots, bettercaptcha, dcaptcha, bcaptcha]
        description: A magickal command