
#
# Dashies Furnace Config thingy Meow!
#

# '<source item> <result item> <result amount>'
# be sure to always specify an amount, if you
# do not it may error.
meltables:
    - 'DIAMOND_SWORD DIAMOND 2'
    - 'GOLDEN_SWORD GOLD_INGOT 2'
    - 'HOPPER IRON_INGOT 4'
    - 'DIAMOND_PICKAXE DIAMOND 3'
    
    
# what permission is required for the use of the commands
# that are available?
command-permission: 'dashsmelter.command'