# Author: Dashie
# Version: 1.0
name: EasyGUICaptcha
version: 1.0
main: com.kvinnekraft.EasyGUICaptcha
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Secure your server properly.
website: https://pugpawz.com

commands:
  EasyGUICaptcha:
    aliases: [egc, captcha, dashcaptcha, easycaptcha greatcaptcha, guicaptcha]
    description: Oh, what is this?
