# Author: Dashie
# Version: 1.0
name: EasyGUICaptcha
version: ${project.version}
main: com.kvinnekraft.EasyGUICaptcha
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Secure your server properly.
website: https://pugpawz.com

commands:
  EasyGUICaptcha:
    aliases: []
    description: Oh, what is this?
