# Author: Dashie
# Version: 1.0
name: DashMobSpawn
version: ${project.version}
main: com.kvinnekraft.DashMobSpawn
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Custom mob spawns
website: https://pugpawz.com