
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.IntervalCommands

api-version: 1.13
version: 1.0

commands:
  intervalcommands:
    aliases: [intervalcommand, ic, intcommand]
    description: By KvinneKraft.

author: [Dashie, KvinneKraft, ME]
name: IntervalCommands
