notify-blocks:
  - 'DIAMOND_ORE'
  - 'GOLD_ORE'
  - 'EMERALD_ORE'
  - 'SPAWNER'
  - 'CHEST'
  - 'TRAPPED_CHEST'
  - 'LAPIS_ORE'
  - 'REDSTONE_ORE'
block-rewards:
  1:
    block-type: 'IRON_ORE'
    rewards:
      - 'IRON_ORE 1 10'
  2:
    block-type: 'GOLD_ORE'
    rewards:
      - 'GOLD_ORE 1 15'
  3:
    block-type: 'COAL_ORE'
    rewards:
      - 'COAL 1 35'
  4:
    block-type: 'DIAMOND_ORE'
    rewards:
      - 'DIAMOND_ORE 1 15'
  5:
    block-type: 'EMERALD_ORE'
    rewards:
      - 'EMERALD 2 15'
  6:
    block-type: 'STONE'
    rewards:
      - 'COAL 1 5'
      - 'IRON_INGOT 1 5'
  7:
    block-type: 'GRASS'
    rewards:
      - 'POTATO 1 2'
      - 'CARROT 1 2'
      - 'WHEAT_SEEDS 1 2'
  8:
    block-type: 'GRASS_BLOCK'
    rewards:
      - 'WHEAT_SEEDS 3 2'
      - 'CARROT 2 2'
      - 'POTATO 2 2'