# Author: Dashie
# Version: 1.0
name: DashMiner
version: ${project.version}
main: com.kvinnekraft.DashMiner
api-version: 1.16
authors: [Dashie, KvinneKraft]
description: Dash Miner plugin lol
website: https://pugpawz.com

commands:
  DashMiner:
    aliases: [xray, dashray]
    description: Oh, what is this?
