# Author: Dashie 
# Version: 1.0

main: com.recoded.DashSecurity

api-version: 1.13
version: 1.0

author: [Dashie,KvinneKraft,Freya,WitchCraft,Dash]
name: DashSecSE

commands:
    login:
        aliases: [signin, log, auth]
    register:
        aliases: [reg, regis]
    resetpassword:
        aliases: [resetlogin, respass, resetpass]

# Dash Security Special Edition <--
