
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.MobHealthifier

api-version: 1.13
version: 1.0

author: [Dashie, KvinneKraft, Dash]
name: MobHealthifier

commands:
    mobhealthifier:
        aliases: [healthy, healthifier, mobhealth, mh, health]
        description: A Fluff By KvinneKraft