
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.DeadlyWaters

api-version: 1.13
version: 1.0

commands:
  deadlywaters:
    aliases: [dw, hurtwater, hurtfulwaters, painfulwaters, painfulwater, deadwater, deathwater, dwater, dedwater, dedwatr]
    description: By KvinneKraft.

author: [Dashie, KvinneKraft, Freya, ME, THIS, IS, ALL, ME, Secretive, Piece, Oops]
name: DeadlyWaters