
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.NukeArrows

api-version: 1.13
version: 1.0

name: NukeArrows
author: [Dashie, KvinneKraft, Freya, ME]

commands:
  nukearrows:
    aliases: [nukearr, arrownuke, nuke, nukes, nukearrow]
    description: By KvinneKraft