
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.WorldCommands

name: WorldCommands
author: [Dashie, KvinneKraft, Ponyball]

api-version: 1.13
version: 1.0

commands:
  worldcommands:
    aliases: [wc, worldcommand, wcommands, wcommand, wcs]
    description: By KvinneKraft@protonmail.com